### PR TITLE
An attempt at fixing transduced behavior when closing a stream.

### PR DESCRIPTION
**Pull request by biiwide**
This is an attempt at fixing issue #135.  I'm not certain this is the correct fix, but it does include test cases that exercise the bug.

### CODE REVIEW

**Comment by ztellman** [comment]
Okay, this is more code to fix the problem than I would have expected, but I need to reacquaint myself with the transducer protocol to say for sure.  I'll update once I have some more concrete feedback.

**Comment by biiwide** [comment]
Just calling `(add! (LinkedList.))` seems to work, but I wasn't sure whether the returned value could be ignored or if it needed to be handled the same as the result in `.put()`.

**Comment by ztellman** [comment]
Sorry for the slow review, this looks good.

**Comment by biiwide** [comment]
Glad I could help.  I really enjoy using this.

**Pull request merged**
